// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCraBIZkD6EPY5um0Zm8SlEzxae6QHq4MM',
    appId: '1:254826835953:web:85a49c6b485cdb0e92de50',
    messagingSenderId: '254826835953',
    projectId: 'new-project-66cad',
    authDomain: 'new-project-66cad.firebaseapp.com',
    storageBucket: 'new-project-66cad.appspot.com',
    measurementId: 'G-0QCJLXHB9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANmvLV8Zm3TZ3AqC6m-hK8Q4-KQ1gkj4M',
    appId: '1:254826835953:android:1eb22553272e847592de50',
    messagingSenderId: '254826835953',
    projectId: 'new-project-66cad',
    storageBucket: 'new-project-66cad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8wtH_LDsfTgKiZ0X275e4TvG88dssOso',
    appId: '1:254826835953:ios:46d162615525307192de50',
    messagingSenderId: '254826835953',
    projectId: 'new-project-66cad',
    storageBucket: 'new-project-66cad.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8wtH_LDsfTgKiZ0X275e4TvG88dssOso',
    appId: '1:254826835953:ios:5c2a74e09930396d92de50',
    messagingSenderId: '254826835953',
    projectId: 'new-project-66cad',
    storageBucket: 'new-project-66cad.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
